name: Build and Package Qt Application

on:
  push:
    branches:
      - main  # Replace with your main branch name
  pull_request:
    branches:
      - main  # Replace with your main branch name

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Visual Studio Build Tools
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Set up Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.15.2'  # Specify the Qt version you need
        host: 'windows'
        target: 'desktop'
        setup-python: true

    - name: Build project
      run: |
        # Navigate to the directory containing the .pro file
        cd TicTacToeProjectfinal/TicTacToeProject
        
        # Run qmake to generate the makefile
        qmake TicTacToeProject.pro
        
        # Build the project to create the .exe file
        nmake

    - name: Deploy Qt dependencies
      run: |
        # Specify the path to the windeployqt executable
        $windeployqtPath = "$Env:Qt5_15_2_MSVC2019_64_BIN\windeployqt.exe"
        
        # Verify the path exists
        if (-Not (Test-Path $windeployqtPath)) {
          throw "windeployqt not found at $windeployqtPath"
        }
        
        # Deploy Qt dependencies to the directory with the .exe
        & $windeployqtPath TicTacToeProjectfinal/TicTacToeProject/release/TicTacToeProject.exe
        
        # Check for errors
        if ($LASTEXITCODE -ne 0) {
          throw "windeployqt failed with exit code $LASTEXITCODE"
        }

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: TicTacToeExecutable
        path: |
          TicTacToeProjectfinal/TicTacToeProject/release/**  # Adjust the path to include all necessary files

    - name: Cleanup
      run: |
        Remove-Item -Path "TicTacToeProjectfinal/TicTacToeProject/release/*" -Force -Recurse
        Remove-Item -Path "TicTacToeProjectfinal/TicTacToeProject/debug/*" -Force -Recurse
