name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Replace with your main branch name
  pull_request:
    branches:
      - main  # Replace with your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Qt dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          libgl1-mesa-dev \
          qtbase5-dev \
          qtchooser \
          qt5-qmake \
          qtbase5-dev-tools \
          libqt5widgets5 \
          libqt5network5

    - name: Build project
      run: |
        qmake TicTacToeProjectfinal/TicTacToeProject/TicTacToeProject.pro
        make

    

    - name: Deploy
      if: success() && github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        # Deployment steps (e.g., upload artifacts, deploy to a server)

    - name: Cleanup
      run: |
        make clean  # Clean up build artifacts
