name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Replace with your main branch name
  pull_request:
    branches:
      - main  # Replace with your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Qt dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libgl1-mesa-dev

    - name: Install Qt
      run: |
        sudo apt-get install -y qt5-default qtbase5-dev qtdeclarative5-dev qttools5-dev-tools

    - name: Build project
      run: |
        qmake -qt=qt5
        make

  
    - name: Deploy
      if: success() && github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        # Deployment steps (e.g., upload artifacts, deploy to a server)

    - name: Cleanup
      run: |
        make clean  # Clean up build artifacts
